FROM postgres:16-bookworm

ARG PGVECTOR_VERSION=v0.8.0
ARG APACHE_AGE_VERSION=release/PG16/1.5.0

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    build-essential \
    git \
    flex \
    bison \
    postgresql-server-dev-16 \
  && git clone --depth 1 --branch ${PGVECTOR_VERSION} https://github.com/pgvector/pgvector.git /tmp/pgvector \
  && make -C /tmp/pgvector \
  && make -C /tmp/pgvector install \
  && git clone --depth 1 --branch ${APACHE_AGE_VERSION} https://github.com/apache/age.git /tmp/age \
  && make -C /tmp/age PG_CONFIG=/usr/lib/postgresql/16/bin/pg_config \
  && make -C /tmp/age install PG_CONFIG=/usr/lib/postgresql/16/bin/pg_config \
  && rm -rf /tmp/pgvector /tmp/age \
  && apt-get purge -y --auto-remove \
    build-essential \
    git \
    flex \
    bison \
    postgresql-server-dev-16 \
  && rm -rf /var/lib/apt/lists/*

COPY docker/postgres/init /docker-entrypoint-initdb.d/
